<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dat</string>
	</array>
	<key>name</key>
	<string>Simutrans Dat</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>everything after # is a comment</string>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.text.simutrans_dat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers for imagetype.#.#,#,#</string>
			<key>match</key>
			<string>[.,](\d+)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>
				parameters where values don't need colour
				cursor, icon
			</string>
			<key>match</key>
			<string>^[cC]ursor|[iI]con</string>
			<key>name</key>
			<string>entity.name.tag.parameter.simutrans_dat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
				parameters with any numeric values
				animation_time, animation_time_open, animation_time_closed, axle_load, build_time, capacity, catg, chance, clusters, cost, dims, distributionweight, electricity_amount, electricity_boost, electricity_demand, expand_minimum, expand_probability, expand_range, expand_times, fixed_cost, gear, hq_level, intro_year, level, length, loading_time, mail_boost, mail_demand, maintenance, max_fields, max_height, max_length, max_lenght, max_weight, min_fields, min_speed, offset_left, passengers, passenger_boost, passenger_demand, payload, pax_level, pillar_distance, power, probability_to_spawn, productivity, range, retire_year, runningcost, smokeoffset, smoketile, smokespeed, sound_nr, speed_bonus, start_fields, station_capacity, station_maintenance, station_price, system_type, topspeed, value, weight, weight_per_unit
			</string>
			<key>match</key>
			<string>(^(([mM]ax_[lL]enght)|([lL]evel)|([sS]tation_([cC]apacity|maintenance))|([sS]tation_[pP]rice)|([eE]lectricity_[aA]mount)|[aA](xle_[lL]oad|nimation_[tT]ime(_([oO]pen|[cC]losed))?)|[bB]uild_[tT]ime|[cC](apacity|atg|hance|lusters)|([fF]ixed_|[rR]unning)?[cC]ost|[dD](ims|istribution[wW]eight)|[eE]xpand_([pP]robability|[mM]inimum|[rR]ange|[tT]imes)|([eE]lectricity|[pP]assenger|[mM]ail)_([bB]oost|[dD]emand)|[gG]ear|[hH][qQ]_[lL]evel|([iI]ntro|[rR]etire)_year|[lL](ength|oading_[tT]ime)|[mM](aintenance|ax_([fF]ields|[hH]eight|[lL]ength|[wW]eight)|in_([fF]ields|[sS]peed))|[oO]ffset_[lL]eft|[pP](assengers|ay[lL]oad|ax_[lL]evel|illar_[dD]istance|ower|robability_[tT]o_[sS]pawn|roductivity)|[sS](moke([oO]ffset|[tT]ile|[sS]peed)|peed_[bB]onus|ound_[nN]r|tart_[fF]ields|ystem_[tT]ype)|[rR]ange|[tT]op[sS]peed|[vV]alue|[wW]eight(_per_unit)?))\b([ \t]*=[ \t]*[-]?(\d+)\b)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.parameter.use-max_length.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.parameter.use-passengers.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.parameter.drop-station_.simutrans_dat</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.parameter.use-cost.simutrans_dat</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.parameter.use-electricity_demand.simutrans_dat</string>
				</dict>
				<key>28</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>
				parameters with boolean values
				draw_as_ding, enables_pax, enables_post, enables_ware, end_of_choose, free_route, is_longblocksignal, is_presignal, is_private, is_signal, needs_ground, no_foreground, noconstruction, noinfo, own_waytype, pillar_asymmetric, single_way, trees_on_top
			</string>
			<key>match</key>
			<string>(^([dD]raw_[aA]s_[dD]ing|[eE](nables_([pP](ax|ost)|[wW]are)|nd_[oO]f_[cC]hoose)|[fF]ree_[rR]oute|[iI]s_([pP]rivate|([lL]ong[bB]lock|[pP]re)?[sS]ignal)|[nN](eeds_[gG]round|o(_[fF]oreground|[cC]onstruction|[iI]nfo))|[oO]wn_[wW]aytype|[pP]illar_[aA]symmetric|[sS]ingle_[wW]ay|[tT]rees_[oO]n_[tT]op))\b([ \t]*=[ \t]*((0|1)|(true|false))$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>
				parameters with string values
				copyright, freight, metric, smoke, sound, sound_name, way
			</string>
			<key>match</key>
			<string>(^([cC]opyright|[fF]reight|[mM]etric|[sS](moke|ound(_name)?)|[wW]ay))\b([ \t]*=[ \t]*([ -.+\w]+))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>fields, freightimagetype, inputgood, inputsupplier, outputgood, outputsupplier parameter</string>
			<key>match</key>
			<string>(^([fF](ields|reight[iI]mage[tT]ype)|([iI]n|[oO]ut)put([gG]ood|[sS]upplier))(\[(\d+)\])?)([ \t]*=[ \t]*([ -.+\w]+))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>inputcapacity, inputfactor, outputcapacity, outputfactor, production_per_field, spawn_weight, storage_capacity parameter</string>
			<key>match</key>
			<string>(^(([iI]n|[oO]ut)put([cC]apacity|[fF]actor)|[pP]roduction_[pP]er_[fF]ield|[sS](pawn_[wW]eight|torage_[cC]apacity))(\[(\d+)\])?)([ \t]*=[ \t]*(\d+)\b)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>allow_underground parameter</string>
			<key>match</key>
			<string>(^[aA]llow_[uU]nderground)([ \t]*=[ \t]*(0|1|2)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>climates parameter</string>
			<key>begin</key>
			<string>(^[cC]limates)</string>
			<key>end</key>
			<string>\n</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([aA]rctic|[dD]esert|[mM]editerran|[rR]ocky|[tT](emperate|ropic|undra)|[wW]ater)</string>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>constraint parameter</string>
			<key>match</key>
			<string>(^[cC]onstraint(\[([nN]ext|[pP]rev)\])?(\[(\d+)\])?)([ \t]*=[ \t]*([ -.+\w]+))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.value.use-tram_track.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>engine_type parameter</string>
			<key>match</key>
			<string>(^[eE]ngine_[tT]ype)([ \t]*=[ \t]*([bB](attery|io)|[dD]iesel|[eE]lectric|[fF]uel_[cC]ell|[hH]ydrogene|[sS](ail|team)|[uU]nknown)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>extension_building parameter</string>
			<key>match</key>
			<string>(^[eE]xtension_[bB]uilding)</string>
			<key>name</key>
			<string>invalid.parameter.does-not-compile.simutrans_dat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>has_snow parameter</string>
			<key>match</key>
			<string>(^[hH]as_[sS]now(\[(\d+)\])?)([ \t]*=[ \t]*((0|1)|(true|false))$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>intro_month, retire_month parameter</string>
			<key>match</key>
			<string>(^([iI]ntro|[rR]etire)_month)([ \t]*=[ \t]*([0-9]|10|11|12)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>location parameter</string>
			<key>match</key>
			<string>(^[lL]ocation)([ \t]*=[ \t]*([cC]ity|[lL]and|[wW]ater)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>mapcolor parameter</string>
			<key>match</key>
			<string>(^[mM]ap[cC]olor)([ \t]*=[ \t]*(25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>name parameter</string>
			<key>begin</key>
			<string>(^[nN]ame)</string>
			<key>end</key>
			<string>(kraftwerk)?\n</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.value.simutrans_dat</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[ \t]*=[ \t]*([-_.+a-zA-Z\d]+(?=kraftwerk\n))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.value.name-parameter.simutrans_dat</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>[ \t]*=[ \t]*([-_.+a-zA-Z\d]+(?!kraftwerk\n))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.value.simutrans_dat</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>obj parameter</string>
			<key>match</key>
			<string>(^[oO]bj)([ \t]*=[ \t]*([bB](ridge|uilding)|[cC](ity[cC]ar|rossing|ursor)|[fF](actory|ield)|[gG](ood|round(_[oO]bj)?)|[mM](enu|isc)|[pP]edestrian|[rR]oad[sS]ign|[sS](moke|ound|ymbol)|[tT](ree|unnel)|[vV]ehicle|[wW]ay([-][oO]bject)?)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>seasons parameter</string>
			<key>match</key>
			<string>(^[sS]easons)([ \t]*=[ \t]*(1|2|4|5)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>speed parameter</string>
			<key>match</key>
			<string>(^[sS]peed(\[(0|1)\])?)([ \t]*=[ \t]*(\d+)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>type parameter</string>
			<key>match</key>
			<string>(^[tT]ype)([ \t]*=[ \t]*(([hH]abour)|([fF]ac)|(([bB]us|[cC]ar|[mM]onorail|[rR]ail)stop|[aA]irport|[hH]all|[pP]ost|[sS](hed|tation)|[wW]harf)|[aA]ny|[cC](om|ur)|[dD](epot|ock)|[eE]xtension|[hH](arbour|q)|[iI]nd|[mM]on|[rR]es|[sS]top|[tT]ow)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.value.use-harbour.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.value.not-needed-automatically-assigned.simutrans_dat</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid.value.does-not-compile.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>waytype parameter</string>
			<key>match</key>
			<string>(^[wW]ay[tT]ype(\[(0|1)\])?)([ \t]*=[ \t]*(([sS]chiene_[tT]ram)|[nN]one|[aA]ir|[pP]ower|[rR]oad|[wW]ater|(([eE]lectrified|[mM](aglev|ono[rR]ail)|[nN]arrow[gG]auge|[tT]ram)_)?[tT]rack)$)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.value.use-tram_track.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>(front|back)Pillar(2)? parameters</string>
			<key>match</key>
			<string>(^([bB]ack|[fF]ront)[pP]illar2?(\[([sSwW])\])?(\[(\d+)\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>(front|back)(Start|Ramp)(2)? parameters</string>
			<key>match</key>
			<string>(^([bB]ack|[fF]ront)([rR]amp|[sS]tart)2?(\[([nNsSeEwW])\])?(\[(\d+)\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>(front|back)image2 parameters</string>
			<key>match</key>
			<string>(^([bB]ack|[fF]ront)[iI]mage2(\[([nN][sS]|[eE][wW])\])?(\[(\d+)\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>(front_)?(open|close)image parameters</string>
			<key>match</key>
			<string>(^([fF]ront_)?([oO]pen|[cC]lose)[iI]mage(\[([nN][sS]|[eE][wW])\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>emptyimage parameters</string>
			<key>match</key>
			<string>(^[eE]mpty[iI]mage(\[(([nN]|[sS])([eEwW])?|[eE]|[wW])\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>(front|back)?imageUp(2)? parameters</string>
			<key>match</key>
			<string>(^([bB]ack|[fF]ront)?[iI]mage[uU][pP]2?(\[([369]|12)\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>(front|back)?diagonal parameters</string>
			<key>match</key>
			<string>(^([bB]ack|[fF]ront)?[dD]iagonal(\[(([nN]|[sS])([eE]|[wW]))\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>freightimage parameters</string>
			<key>match</key>
			<string>(^[fF]reight[iI]mage(\[(\d)+\])?(\[(([nN]|[sS])([eEwW])?|[eE]|[wW])\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>image parameters</string>
			<key>match</key>
			<string>(^[iI]mage(\[((\d+)|([-]|[wW]|[eE][wW]?|[sS]([wW]|[eE]([wW](1|2)?)?)?|[nN]([wW]|[eE]([wW](1|2)?)?|[sS]([wW](1|2)?|[eE](1|2|[wW](1|2)?)?)?)?))\])?(\[(\d+)\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>17</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>backimage parameters</string>
			<key>match</key>
			<string>(^[bB]ack[iI]mage(\[((\d+)|([-]|[nN]([eE]([wW])?|[wW]|[sS]([wW]|[eE]([wW])?)?)|[eE][wW]|[sS]([wW]|[eE]([wW])?)|([nN]|[sS]|[eE]|[wW])([lL]|[mM]|[rR])?))\])?(\[(\d+)\])?(\[(\d+)\])?(\[(\d+)\])?(\[(\d+)\])?(\[(\d+)\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>15</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>17</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>19</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>21</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>23</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>frontimage parameters</string>
			<key>match</key>
			<string>(^[fF]ront[iI]mage(\[((\d+)|([-]|([nN]|[sS]|[eE]|[wW])([lL]|[mM]|[rR])?|[eE][wW]|[sS]([wW]|[eE]([wW](1|2)?)?)|[nN]([wW]|[eE]([wW](1|2)?)?|[sS]([wW](1|2)?|[eE](1|2|[wW](1|2)?)?)?)))\])?(\[(\d+)\])?(\[(\d+)\])?(\[(\d+)\])?(\[(\d+)\])?(\[(\d+)\])?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.parameter.simutrans_dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.value.simutrans_dat</string>
				</dict>
				<key>19</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>21</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>23</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>25</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
				<key>27</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.value.simutrans_dat</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.simutrans_dat</string>
	<key>uuid</key>
	<string>294467ff-eac0-4e4f-ae82-8dde860560bb</string>
</dict>
</plist>
